language: java
jdk: oraclejdk8
script: ./test-all-versions.sh
install: mvn install -DskipTests=true -Dgpg.skip=true
after_success: ./push-javadoc-to-gh-pages.sh
env:
    global:
        secure: HGMOQhzhP8ghdUoN3Wf1kOiDZ3JUjmUtHThX8VHrug1b8xSeIwSiV1AmoRp8ilm9sTy3Lt7ywRdqmu8OP5Y1B8vojrNIcB7QInZ3FBOalWWBLmJBhQ5sHTL8Fy4d7zRwMU19xSVEfNxRHn/KazUlJdofeQ1q0OJMfNrZjHUyE6tNQEtQ5xSm1Ix1e9R4+zHQobs0XIrZXRnuSlVocMAJw5wSKJmdQn9XPQfwceyouOn2qYs7p++vmu5Amt+tEJ/Hdk1J2UVN2/1bNVzA32GZR58DqZrdx522r9JM2eMzmcPz1JNjFLjqIINWmRqi2bT5MA2TL4NqAlzC8fvaw+d889EVRdE3qhBHLvN93E/HBcd1sV7LvqlGtZP26VCtjTsg/dGp4nspUEag4Nd/i16qoaf/QuWjc6xOcVLiREixMlirFRY+383xtCRlQGRZwcSIR1aZd2Ok9AdsjP3fStJKvAifGqA2BAC3ZEV4u171oEqssxbsAMmOUmK9wlcyPLM7NH+KgJXL/pAdu33aS14msrr3Rrfe52B8P6TtrBlqvLGsDLVJdubOUw+xVUEp6Xwa8RAoL+E8RUAqLiY6Z59IifPxwoSbsBDOWSgahYc0Kc6NNnJvXFuMg9Nu1djB8FxLtU2YGDCpDX+Ua18FbU900zO3BfcMiZA0+7ggSbT+ZCQ=
